### ISSUE TITLE
Suggestion: Add a way of handling subsequent async assertions

### ISSUE THREAD

**Issue by cristijora** [wrseward/vue-unit#1]
First of all thanks for the repo. It really helps hiding a lot of boilerplate code when writing unit tests.

By default when changes are triggered on data you have to use `$nextTick` in order to verify the expected output.
Example:
```js
vm.msg= "some value"
vm.$nextTick(()=>{
 //verify that DOM changed here
 vm.msg = "some other value"
 vm.$nextTick(()=>{
 //verify that DOM changed here for the second message update
  done(); //call done callback for the test
 })
})
```

Such a way of testing updates can become really cumbersome and ugly. Maybe adding a helper method that will be exposed in the library like [waitForUpdate](https://github.com/vuejs/vue/blob/dev/test/helpers/wait-for-update.js) from vue repo.
The usage would be:
```js
waitForUpdate(() => {
   expect(vm.$el.textContent).toBe('123')
   vm.a = 234
 })
.then(() => {
   // more assertions...
 })
.then(done)
```
This can be refined of course so it fits vue-unit better.

**Comment by wrseward** [comment]
Thank you so much for the suggestion! **I love it** and didn't even know this existed. I think it fits well as is too.

What are your thoughts just copying over this implementation of helper for now? So it would exposed like:

```js
import { waitForUpdate } from 'vue-unit'
```

**Comment by wrseward** [comment]
Apparently the waitForUpdate from Vue's test helpers is well suited for jasmine but not mohca. I'll definitely work on an implementation though, to ease the repetitive nextTick chaining.

**Comment by cristijora** [comment]
My initial thought was indeed yo expose it as a helper function as you described 
`import { waitForUpdate } from 'vue-unit'` . May I know why it's not well suited for mocha and what is the problem exactly ?

**Comment by wrseward** [comment]
With mocha the example given would have to use the `.end(done)` instead of `.then(done)`, otherwise [this error](https://github.com/vuejs/vue/blob/350eb0f02974f7ccbafbad81e2c86f167a00cbd7/test/helpers/wait-for-update.js#L44) gets thrown.

So the above would have to look like this in mocha:

```js
waitForUpdate(() => {
   expect(vm.$el.textContent).toBe('123')
   vm.a = 234
 })
.then(() => {
   // more assertions...
 })
.end(done)
```

It might be a good enough trade-off for now, but ideally I'd like to reconcile that to keep it consistent between mocha and jasmine before releasing into vue-unit. I am going to work on something for this tonight.

Thoughts?

**Comment by cristijora** [comment]
Indeed that implementation works out of the box with jasmine only after testing myself. Is it possible to have `end(done)` for both ? If yes, I guess that wold be an option

**Comment by wrseward** [comment]
Added to v0.2.0
