### ISSUE TITLE
Whether it must be installed Vuex ?

### ISSUE THREAD

**Issue by hejianxian** [wrseward/vue-unit#2]
Hi! Thanks for your repo! 👍 

In my project, did not use `vuex`. when I run the unit test, it throw a warning. 

```js
WARNING in ./~/vue-unit/build/index.js
Module not found: Error: Cannot resolve module 'vuex' in /Users/name/Documents/project/node_modules/vue-unit/build
```

Does that mean `vuex` should be a pre-dependent?

**Comment by wrseward** [comment]
Apparently webpack will warn (not error) if it can't resolve a module, even if inside a try/catch block. I am not sure if there a webpack configuration that would help with this, but I think I might just make vuex a peer dependency for now.
