### ISSUE TITLE
Failing tests in waitForUpdate chains time out in Mocha

### ISSUE THREAD

**Issue by tom-kitchin** [wrseward/vue-unit#4]
When run in Mocha, using waitForUpdate with a failing test results in the async call timing out.

This is because the waitForUpdate code assumes that the `done` call will have `done.fail` and checks for that, but Mocha uses `done(e)` to report failures.

PR to resolve: https://github.com/wrseward/vue-unit/pull/3

**Comment by wrseward** [comment]
Thanks for both reporting **and** fixing this! 👍
